site_name: 依智而動者與人相衝，依情而行者隨波逐流。

theme:
  name: material
  language: zh-TW
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github 
  features:
    - navigation.indexes
    - navigation.tabs

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - tags:
      tags_file: tags.md
  - glightbox

repo_url: https://github.com/aquastripe/notes
repo_name: aquastripe/notes

nav:
  - "Math":
    - "Probability Theory":
      - "KL Divergence": math/probability/kl_divergence.md
  - "Deep Learning":
    - "Generative Models":
      - "Introduction": deep-learning/generative-models/introduction.md
      - "Variational Inference": deep-learning/generative-models/variational-inference.md
  # - "Paper":
  - Tags: "tags.md"

copyright: Copyright &copy 2023 Hao-Ting Li. Content on this site is licensed under a <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a>.
